# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

# 获取当前目录
current_dir = os.path.dirname(os.path.abspath(SPEC))

a = Analysis(
    ['start.py'],
    pathex=[current_dir],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('config.py', '.'),
        ('models.py', '.'),
        ('m3u8_processor.py', '.'),
        ('app.py', '.'),
    ],
    hiddenimports=[
        'flask',
        'flask.templating',
        'flask_cors',
        'flask_sqlalchemy',
        'requests',
        'm3u8',
        'pycryptodomex',
        'urllib3',
        'colorlog',
        'sqlite3',
        'threading',
        'uuid',
        'json',
        'datetime',
        'pathlib',
        'subprocess',
        'webbrowser',
        'werkzeug',
        'werkzeug.security',
        'jinja2',
        'markupsafe',
        'itsdangerous',
        'click',
        'blinker',
        'sqlalchemy',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.pool',
        'email_validator',
        'wtforms',
        'platform',
        'time',
        'os',
        'sys',
        'urllib.parse',
        'concurrent.futures',
        'queue',
        'logging',
        'traceback',
        'functools',
        'collections',
        're',
        'base64',
        'hashlib',
        'hmac',
        'secrets',
        'tempfile',
        'shutil',
        'glob',
        'mimetypes',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
        'torch',
        'tensorflow',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Flask-M3U8-Manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(current_dir, 'static', 'favicon.ico') if os.path.exists(os.path.join(current_dir, 'static', 'favicon.ico')) else None,
)
